In [1]:
import numpy as np, pandas as pd
from matplotlib.pyplot import subplots
from sklearn.linear_model import (LinearRegression, LogisticRegression, Lasso)
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from ISLP import load_data
from ISLP.models import ModelSpec as MS
from sklearn.model_selection import (train_test_split, GridSearchCV)

In [2]:
import torch
from torch import nn
from torch.optim import RMSprop
from torch.utils.data import TensorDataset

In [3]:
from torchmetrics import (MeanAbsoluteError, R2Score)
from torchinfo import summary
from torchvision.io import read_image

In [6]:
from torchvision.datasets import MNIST, CIFAR100
from torchvision.models import (resnet50, ResNet50_Weights)
from torchvision.transforms import (Resize,
                                    Normalize,
                                    CenterCrop,
                                    ToTensor)

In [7]:
(mnist_train, mnist_test) = [MNIST(root='data',
                                      train=train,
                                      download=True,
                                      transofrm=ToTensor())
                                      for train in [True, False]]

TypeError: MNIST.__init__() got an unexpected keyword argument 'transofrm'

In [9]:
import numpy as np

# Example matrix
matrix = np.array([
    [10, 40, 30, 20],
    [5, 15, 25, 35],
    [8, 18, 28, 38]
])

# Get the indices of the three largest values in each row, sorted in descending order
top_3_indices = np.argsort(matrix, axis=1)[:, -3:][:, ::-1]

print(top_3_indices)


[[1 2 3]
 [3 2 1]
 [3 2 1]]


### Neural Networks - One Hot Encoding

In [10]:
import keras
from keras import layers